// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDICmA1SldP9vrlZl_sgsJSGEx8Q5rMUVU',
    appId: '1:908421990166:web:92f90a843a02226441f237',
    messagingSenderId: '908421990166',
    projectId: 'smartvigie-66644',
    authDomain: 'smartvigie-66644.firebaseapp.com',
    storageBucket: 'smartvigie-66644.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA-oLGEq7VVQXHEXwxlZxHRfO_HtXiw20',
    appId: '1:908421990166:android:1e9aaf129f325dc741f237',
    messagingSenderId: '908421990166',
    projectId: 'smartvigie-66644',
    storageBucket: 'smartvigie-66644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ckWWF0qRyZHUS6UIkxHoHi22doeTmqU',
    appId: '1:908421990166:ios:6ec57b0ad37bbdc841f237',
    messagingSenderId: '908421990166',
    projectId: 'smartvigie-66644',
    storageBucket: 'smartvigie-66644.firebasestorage.app',
    iosBundleId: 'com.example.smartVigie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDICmA1SldP9vrlZl_sgsJSGEx8Q5rMUVU',
    appId: '1:908421990166:web:b83123cc5b895dcf41f237',
    messagingSenderId: '908421990166',
    projectId: 'smartvigie-66644',
    authDomain: 'smartvigie-66644.firebaseapp.com',
    storageBucket: 'smartvigie-66644.firebasestorage.app',
  );
}
